
PREFIX=/usr/local
BINDIR=$(DESTDIR)$(PREFIX)/bin

CC=gcc
CFLAGS=-O3 -Wall -I../modules/mqnic

BIN=cookie_test

all: $(BIN)

cookie_test: mqnic-config.c mqnic.c timespec.c
	$(CC) $(CFLAGS) $^ -o $@

install:
	install -d $(BINDIR)
	install -m 0755 $(BIN) $(BINDIR)

clean:
	rm -f $(BIN)


PREFIX=/usr/local
BINDIR=$(DESTDIR)$(PREFIX)/bin

CC=gcc
CFLAGS=-fPIC -O3 -Wall -I../modules/mqnic
LDFLAGS=-shared

TARGET = mqnic.so

all: $(TARGET)

mqnic.so: mqnic.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $(TARGET)
